### ISSUE TITLE
Cannot pass event PlayerCommandPreproccessEvent...

### ISSUE THREAD

**Issue by Tqri** [dvargas135/eZProtector#59]
Apparently eZProtector is working (changes to config work like custom messages) but commands like /? work despite being blocked.

Error (comes up in console whenever a command is done) - [https://pastebin.com/A7YgmpJZ](url)
Configuration File - [https://pastebin.com/aKRrP4vc](url)

**Comment by DoNotSpamPls** [comment]
If you read this, try the newest version of eZProtector and let me know how it goes and if there is still an issue.

**Comment by CloudeLecaw** [comment]
hm i cheated with my commands.yml as extra protection you may should Thing About adding a simmlar feature :-D

```
command-block-overrides: []
unrestricted-advancements: false
aliases:
  icanhasbukkit:
  - help
  about:
  - help
  version:
  - help
  ver:
  - help
  '?':
  - help
  a:
  - help
```
